### ISSUE TITLE
Option key label shrinking on long option text

### ISSUE THREAD

**Issue by juliushuck** [quillforms/quillforms#170]
**Describe the bug**
Option key label shrinking on long option text. Please add flex-shrink: 0 or sth else to .multipleChoice__optionKey

**Screenshots**
![Screenshot 2024-03-18 at 00 39 54](https://github.com/quillforms/quillforms/assets/41862965/992da9c8-cb24-4e63-b62d-3bda1525a9d9)

PS: I also had to set the following code to quick fix some nasty overflow on the welcome screen

```css
.qf-welcome-screen-block__content-wrapper {
  min-height: calc(100% - 60px) !important;
}
```
